## Numpy Snippets for Sessions

This notebook contains extra slides & snippets:

In [2]:
list_ = [1, 2, 3, 4]

In [3]:
dir(list_)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [4]:
len(list_)

4

In [5]:
list_.__len__()

4

***
## Needs of a Data Scientist:

(Shamelessly plagiarized from [Scipy's Tutorial](https://www.scipy-lectures.org/intro/intro.html#the-scientific-python-ecosystem))

* Get data to satisfy one's need to be able to run experiments.
* Manipulate and process data in a quick and easy way.
* Visualize results, quickly to understand, but also with high quality figures.
* To do Machine Learning!
* Deploy those models:
   * As API
   * As Dashboards/WebApps

***

## Python solves a lot of the above problems:

Sure it doesn't have out of the box solutions like __R or Matlab__, but it does things!

* `requests` to access data sources that are APIs
* SQL Connections packages: e.g. `psycopg2` for PostGresql databases
* `numpy` and `pandas` for data manipulations
* `matplotlib`, `seaborn`, `altair` for visualizations
* `scikit-learn` to do Machine Learning!
* `pymcmc`, `prophet` and a few other specific packages that deal with varied types of problems
* Wide array of Web Frameworks that help with deploying Machine Learning models as API: `flask`, `django`, `falcon`, `vibora`, `hug`, `responder`!
* To create dashboards or web applications, pure python implementations include: `bokeh` and an newer library called `Dash`.
* `boto3` for AWS/GCP Infrastructure provisioning

## The list is endless!

## Oh and JUPYTER effin NOTEBOOKS!

***

__ndarray__ essentially is an n-dimensional array

## Numpy Code Snippets:


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners. To disable this behaviour: `np.set_printoptions(threshold=np.nan)`

In [3]:
import numpy as np

## Creating an ndarray from a list

In [4]:
# From list: 1d array
my_list = [10, 20, 30]
np.array(my_list)

array([10, 20, 30])

## What if we wanted to multiply 2 to each element of the original list?

In [5]:
my_list

[10, 20, 30]

In [6]:
my_array = np.array(my_list)

In [7]:
my_array

array([10, 20, 30])

In [8]:
my_array * 2

array([20, 40, 60])

## Type Casting for numpy arrays!

* Each element in a numpy array needs to be the same
* Unlike lists where it's "Aao jao, ghar tumhara", numpy enforces stricter rules
* In a way for the scientific community, it's good
* For the data science community, it's a bit of a pain. Why?

## Convert all the values (elements) in array a to string?

In [9]:
a =  np.array([[1, 2, 3,4,5,6],[7,8,9,10,11,12]]) 
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [10]:
a.astype('str')

array([['1', '2', '3', '4', '5', '6'],
       ['7', '8', '9', '10', '11', '12']], dtype='<U21')

In [45]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## If we want to create an array specifically as an array of string?

In [13]:
dt = np.array([[1, 2], [1, 2]], dtype="str")

In [14]:
dt

array([['1', '2'],
       ['1', '2']], dtype='<U1')

In [15]:
dt.itemsize

4

## What's `<U1`

In [31]:
dt_more = np.array([[1, 2, 1, 1231, 121, 12312], [1, 2, 1, 1231, 121, 12312]], dtype="str")

In [32]:
dt_more

array([['1', '2', '1', '1231', '121', '12312'],
       ['1', '2', '1', '1231', '121', '12312']], dtype='<U5')

In [35]:
dt.itemsize

4

`itemsize`: Length of one array element in bytes.

```bash
'?'	boolean
'b'	(signed) byte
'B'	unsigned byte
'i'	(signed) integer
'u'	unsigned integer
'f'	floating-point
'c'	complex-floating point
'm'	timedelta
'M'	datetime
'O'	(Python) objects
'S', 'a'	zero-terminated bytes (not recommended)
'U'	Unicode string
'V'	raw data (void)
```

In [21]:
dt = np.array(['d'])

In [23]:
dt

array(['d'], dtype='<U1')

In [24]:
dt.itemsize # Byte size

4

In [38]:
dtfloat = np.dtype('float64')

dtfloat.itemsize

In [40]:
dtfloat16 = np.dtype('float16')

dtfloat16.itemsize

In [42]:
dtuint8 = np.dtype('uint8')

dtuint8.itemsize

1

In [44]:
dtuint32 = np.dtype('uint32')

dtuint32.itemsize

4

## Stacking arrays

## Other use cases

1. Like lists we'd like to smash two array together into one!

In [46]:
np.vstack((np.arange(10), np.arange(10)))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
np.hstack((np.arange(10), np.arange(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.column_stack((np.arange(10), np.arange(10)))

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

## Subsetting using vector operations (Refer notebook)

Creating slices from an ndarray to get filtered list

### Subset the array if the temperatures are greater than 0

In [52]:
#[val for val in temperatures.tolist() if val > 0]

## Using filter and lambda

In [53]:
#list(filter(lambda x: x > 0, temperatures))

## Using numpy!

In [63]:
temperatures[temperatures > 0]

array([ 0.19995117,  0.79980469,  1.79980469, ...,  0.60009766,
        0.09997559,  0.19995117], dtype=float16)

## Do not believe me?

In [64]:
len(temperatures[temperatures > 0])

6600

In [65]:
len([val for val in temperatures.tolist() if val > 0])

6600

In [69]:
len(list(filter(lambda x: x > 0, temperatures)))

6600

## How fast are the operations

In [70]:
%timeit -n 1000 [val for val in temperatures.tolist() if val > 0]

631 µs ± 542 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [71]:
%timeit -n 1000 filter(lambda x: x > 0, temperatures)

230 ns ± 0.801 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [74]:
%timeit -n 1000 temperatures[temperatures > 0]

93.7 µs ± 185 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


![](./2011_comparison.png)

## Need to talk about axis

* `numpy` Aggregation Functions that we have are simple 1D arrays are we are happy to do smaller ones
* What if we want to just do directly on an actual `ndarray` that looks like a table?

In pandas, you'd find the below:

>axis : {'index' (0), 'columns' (1)}

* `index` (for ndarray and pandas dataframe) is nothing but `rows` of a table
* `columns` well columns

In [80]:
arr = np.array([[1, 2, 3], [10, 20, 30]])

In [81]:
arr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [82]:
arr.sum(axis=0)

array([11, 22, 33])

In [83]:
arr.sum(axis=1)

array([ 6, 60])

## Other numpy aggregation functions

```bash
Function Name	NaN-safe Version	Description
np.sum	        np.nansum	        Compute sum of elements
np.prod	        np.nanprod	        Compute product of elements
np.mean	        np.nanmean	        Compute mean of elements
np.std	        np.nanstd	        Compute standard deviation
np.var	        np.nanvar	        Compute variance
np.min	        np.nanmin	        Find minimum value
np.max	        np.nanmax	        Find maximum value
np.argmin	    np.nanargmin	    Find index of minimum value
np.argmax	    np.nanargmax	    Find index of maximum value
np.median	    np.nanmedian	    Compute median of elements
np.percentile	np.nanpercentile	Compute rank-based statistics of elements
np.any	        N/A	                Evaluate whether any elements are true
np.all	        N/A	                Evaluate whether all elements are true
```

## Why is this needed?

* First Rule of Data Science Club: ALWAYS DO AN EDA!
* Why nan versions of the functions?
    * Real world datasets are messy: hence you'll find missing values
    * To calculate summary statistics, `NaN` are bleh!

## NaN, None, Null

>`None` is just a value that commonly is used to signify 'empty', or 'no value here'

>nan stands for Not A Number, and this is not equal to 0

In [105]:
np.nan

nan

In [103]:
None

In [104]:
np.nan is None

False

In [106]:
np.isnan(np.nan)

True

In [107]:
np.isnan(None)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [108]:
import pandas as pd

In [109]:
pd.isnull(None)

True

In [110]:
pd.isnull(np.nan)

True

## Play with characters in numpy

In [298]:
weather[:,:1].astype('str')

array([['2012-01-01 00:00:00'],
       ['2012-01-01 01:00:00'],
       ['2012-01-01 02:00:00'],
       ..., 
       ['2012-12-31 21:00:00'],
       ['2012-12-31 22:00:00'],
       ['2012-12-31 23:00:00']],
      dtype='<U20')

In [304]:
weather[:,:1][np.char.find(weather[:,:1].astype('str'), '2012-02-05') == 0]

array([b'2012-02-05 00:00:00', b'2012-02-05 01:00:00',
       b'2012-02-05 02:00:00', b'2012-02-05 03:00:00',
       b'2012-02-05 04:00:00', b'2012-02-05 05:00:00',
       b'2012-02-05 06:00:00', b'2012-02-05 07:00:00',
       b'2012-02-05 08:00:00', b'2012-02-05 09:00:00',
       b'2012-02-05 10:00:00', b'2012-02-05 11:00:00',
       b'2012-02-05 12:00:00', b'2012-02-05 13:00:00',
       b'2012-02-05 14:00:00', b'2012-02-05 15:00:00',
       b'2012-02-05 16:00:00', b'2012-02-05 17:00:00',
       b'2012-02-05 18:00:00', b'2012-02-05 19:00:00',
       b'2012-02-05 20:00:00', b'2012-02-05 21:00:00',
       b'2012-02-05 22:00:00', b'2012-02-05 23:00:00'],
      dtype='|S20')

## Broadcasting

>Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.

__Official Documentation definition__

>The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.

[Source: Broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

In [118]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [119]:
a.shape

(3,)

In [120]:
b.shape

(3,)

In [121]:
c = np.array([9, 4])

### Will we be able to add these two arrays?

In [122]:
a + c

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

### Essentially we can't do other operations on a and c as well

### Remember Matrix operations?

>NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation.

Essentially, if it follows all the matrix operations

In [125]:
c = 2

In [126]:
a + c

array([2, 3, 4])

In [128]:
a * c

array([0, 2, 4])

### Rules of Broadcasting (Source: Jake VanderPlas' Book):


![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [131]:
arr1 = np.ones((3, 3))

In [132]:
arr2 = np.arange(3)

In [133]:
arr1.shape, arr2.shape

((3, 3), (3,))

In [135]:
print(arr1)
print(arr2)
print(arr1 + arr2)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[0 1 2]
[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]


In [137]:
arr3 = np.arange(3).reshape(3, 1)

In [138]:
arr4 = np.arange(3)

In [139]:
print(arr3)
print(arr4)
print(arr3 + arr4)

[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


### Using Broadcasting in weather data, to do `Standardized Scaling (Z Score Scaling)` on `Temp (C)` column

$$z\;=\;\frac{x-\mu}{\sigma}$$
$$where,\;\mu\;=\;mean,\;x\;=\;value(here\;array/column)\;and\;\sigma\;=\;standard\;deviation$$


In [146]:
x = weather[:,1].astype('float')

In [147]:
mean_ = np.nanmean(x)

In [148]:
sigma_ = np.nanstd(x)

In [149]:
z_score = (x - mean_) / sigma_

In [150]:
z_score

array([-0.90681502, -0.90681502, -0.90681502, ..., -0.79558239,
       -0.76991332, -0.7528006 ])

#### `z_score` is the standardized score of the `Temp (C)` column

## Reference, Deep and Shallow Copy

In [238]:
xs = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
ys = list(xs)  # Make a shallow copy

In [239]:
print(xs)
print(ys)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


## Would ys value change if we add something to xs?

In [240]:
xs.append(['new sublist'])
print(xs)
print(ys)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], ['new sublist']]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


## If we change the original xs values, would it change for ys?

In [241]:
xs[1][0] = 'X'
print(xs)
print(ys)

[[1, 2, 3], ['X', 5, 6], [7, 8, 9], ['new sublist']]
[[1, 2, 3], ['X', 5, 6], [7, 8, 9]]


### Similar concept exists in numpy as well as pandas

In [260]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [262]:
arr.shape

(3, 3)

In [263]:
arr_shallow = arr.view()

### Let's change a few properties for Shallow Copy

In [264]:
arr.shape

(3, 3)

In [265]:
arr_shallow.shape

(3, 3)

In [266]:
arr_shallow

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [267]:
arr[1, 1] = 10

In [268]:
arr_shallow

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [269]:
arr

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

## Deep Copy

In [270]:
import copy
xs = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
zs = copy.deepcopy(xs)

In [272]:
print(xs)
print(zs)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [273]:
xs[1][0] = 'X'
print(xs)
print(zs)

[[1, 2, 3], ['X', 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


### Let's change a few properties for Deep Copy

In [274]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_deep = arr.copy()

In [275]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [276]:
arr_deep

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [277]:
arr[1, 1] = 10

In [278]:
arr_deep

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [279]:
arr

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

## Series Use-cases

In [305]:
s = pd.Series(pd.date_range('20130101 09:10:12', periods=4))

In [306]:
s.dt.hour

0    9
1    9
2    9
3    9
dtype: int64

In [307]:
s

0   2013-01-01 09:10:12
1   2013-01-02 09:10:12
2   2013-01-03 09:10:12
3   2013-01-04 09:10:12
dtype: datetime64[ns]

In [308]:
s.dt.month

0    1
1    1
2    1
3    1
dtype: int64

## Row in table == pd.Series